#pragma once

/**
 * @file test_db_helpers.h
 * @brief Backend abstraction helpers for Storm ORM TYPED_TEST infrastructure
 *
 * Provides template helpers keyed on ConnType (SQLite or PostgreSQL) so that
 * all ORM tests can run against both backends from a single binary.
 *
 * PostgreSQL test isolation uses per-process schemas (test_<pid>), giving each
 * CTest process its own namespace. This enables fully parallel execution with
 * zero lock contention — no TRUNCATE, no transaction wrapping, no deadlocks.
 *
 * PostgreSQL tests auto-skip when STORM_PG_CONNSTR env var is not set.
 *
 * Usage in test files:
 *   #include "test_db_helpers.h"
 *   template <typename ConnType>
 *   class MyTest : public ::testing::Test { ... };
 *   TYPED_TEST_SUITE(MyTest, DatabaseTypes);
 */

#include <cstdlib>
#include <gtest/gtest.h>
#include <libpq-fe.h>
#include <regex>
#include <string>
#include <type_traits>

// Forward-declare connection types (actual import in .cpp files via `import storm;`)
// These are used in std::is_same_v checks within if constexpr branches.
namespace storm::db::sqlite {
class Connection;
}
namespace storm::db::postgresql {
class Connection;
}

// Type list for TYPED_TEST_SUITE — runs each test against both backends
using DatabaseTypes = ::testing::Types<storm::db::sqlite::Connection, storm::db::postgresql::Connection>;

namespace storm::test {

namespace detail {
// Tracks the current per-process test schema name.
// Empty means no schema has been created yet for this process.
inline std::string current_test_schema; // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
} // namespace detail

// Check if the backend is available (PG requires STORM_PG_CONNSTR set and server reachable;
// SQLite is always available)
template <typename ConnType> bool backend_available() {
    if constexpr (std::is_same_v<ConnType, storm::db::postgresql::Connection>) {
        const char *connstr = std::getenv("STORM_PG_CONNSTR");
        if (!connstr)
            return false;
        PGconn *conn = PQconnectdb(connstr);
        bool ok = PQstatus(conn) == CONNECTION_OK;
        PQfinish(conn);
        return ok;
    }
    return true;
}

// Get the connection string for the current backend
template <typename ConnType> auto get_connection_string() -> std::string {
    if constexpr (std::is_same_v<ConnType, storm::db::postgresql::Connection>) {
        const char *connstr = std::getenv("STORM_PG_CONNSTR");
        return connstr ? std::string(connstr) : "";
    } else {
        return ":memory:";
    }
}

// Non-template overload for backward compatibility with existing code
inline auto get_connection_string() -> std::string { return ":memory:"; }

// Adapt SQLite-style CREATE TABLE SQL for the current backend
template <typename ConnType> auto adapt_schema(const std::string &sqlite_sql) -> std::string {
    if constexpr (std::is_same_v<ConnType, storm::db::postgresql::Connection>) {
        std::string sql = sqlite_sql;

        // AUTOINCREMENT → GENERATED ALWAYS AS IDENTITY
        // SQLite: "id INTEGER PRIMARY KEY AUTOINCREMENT"
        // PG:     "id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY"
        sql = std::regex_replace(sql, std::regex("AUTOINCREMENT"), "GENERATED BY DEFAULT AS IDENTITY");

        // BLOB → BYTEA
        sql = std::regex_replace(sql, std::regex("\\bBLOB\\b"), "BYTEA");

        // REAL → DOUBLE PRECISION (PG REAL is 4-byte float with ~7 digits;
        // DOUBLE PRECISION matches SQLite's 8-byte double)
        sql = std::regex_replace(sql, std::regex("\\bREAL\\b"), "DOUBLE PRECISION");

        // INTEGER → BIGINT (SQLite INTEGER is always 64-bit;
        // PG INTEGER is 32-bit, BIGINT matches SQLite semantics)
        sql = std::regex_replace(sql, std::regex("\\bINTEGER\\b"), "BIGINT");

        return sql;
    } else {
        return sqlite_sql;
    }
}

// Non-template overload for backward compatibility
inline auto adapt_schema(const std::string &sqlite_sql) -> std::string { return sqlite_sql; }

// Create table with per-process schema isolation for PG, plain CREATE for SQLite.
// On the first call per process, creates a fresh schema (test_<pid>) and sets search_path.
// Subsequent calls in the same process reuse the schema. This gives each CTest process
// its own namespace — zero lock contention, fully parallel execution.
template <typename ConnType> auto ensure_table(auto &conn, const std::string &sqlite_create_sql) {
    if constexpr (std::is_same_v<ConnType, storm::db::postgresql::Connection>) {
        // One-time per-process schema initialization
        if (detail::current_test_schema.empty()) {
            detail::current_test_schema = "test_" + std::to_string(getpid());
            (void)conn->execute("DROP SCHEMA IF EXISTS " + detail::current_test_schema + " CASCADE");
            (void)conn->execute("CREATE SCHEMA " + detail::current_test_schema);
            (void)conn->execute("SET search_path TO " + detail::current_test_schema);
        }
        // Create table in the test schema (fresh schema, no IF NOT EXISTS needed)
        std::string sql = adapt_schema<ConnType>(sqlite_create_sql);
        return conn->execute(sql);
    } else {
        return conn->execute(sqlite_create_sql);
    }
}

// Begin test isolation. For PG: no-op (schema provides isolation).
// For SQLite: no-op (:memory: is inherently isolated).
// Kept for API compatibility — all test SetUp functions call this after ensure_table.
template <typename ConnType> void begin_test_txn(auto &conn, std::initializer_list<const char *> tables) {
    (void)conn;
    (void)tables;
}

// End test isolation. For PG: drops the per-process schema (instant cleanup).
// For SQLite: no-op (:memory: is destroyed with the connection).
template <typename ConnType> void rollback_test_txn(auto &conn) {
    if constexpr (std::is_same_v<ConnType, storm::db::postgresql::Connection>) {
        if (!detail::current_test_schema.empty()) {
            (void)conn->execute("DROP SCHEMA IF EXISTS " + detail::current_test_schema + " CASCADE");
            detail::current_test_schema.clear();
        }
    }
    (void)conn;
}

// Check if we're running against PostgreSQL
template <typename ConnType> constexpr bool is_postgresql() {
    return std::is_same_v<ConnType, storm::db::postgresql::Connection>;
}

// Check if we're running against SQLite
template <typename ConnType> constexpr bool is_sqlite() {
    return std::is_same_v<ConnType, storm::db::sqlite::Connection>;
}

} // namespace storm::test
