#include <gtest/gtest.h>

#include "test_db_helpers.h"

import storm;
import std;

#include "test_models.h" // NOSONAR cpp:S954

// ============================================================================
// #586: caller-assigned integer primary key — DDL is byte-identical to plain
// `storm::primary` on both backends, because the distinction is on the DML
// side (INSERT column list + RETURNING), not the DDL side.
//
// The schema generator has no awareness of primary_assigned — it emits the
// same INTEGER PRIMARY KEY / GENERATED BY DEFAULT AS IDENTITY as it does for
// a plain `primary`. These tests pin that fact and guard against a future
// change widening the DDL branch.
// ============================================================================

namespace {

    struct AssignedIdModel {
        [[= storm::primary_assigned]] int id{};
        std::string                       name;
    };

    // Regression anchor: plain primary must keep its existing DDL.
    struct PlainPrimaryModel {
        [[= storm::primary]] int id{};
        std::string              name;
    };

    // Regression anchor: primary_autoincrement must keep its existing DDL.
    struct AutoincModel {
        [[= storm::primary_autoincrement]] int id{};
        std::string                            name;
    };

} // namespace

TEST(CallerAssignedPkSchemaTest, AssignedPkDdlMatchesPlainPrimarySqlite) {
    const std::string& assigned_sql = storm::create_table_sql<AssignedIdModel>();
    const std::string& plain_sql    = storm::create_table_sql<PlainPrimaryModel>();

    auto extract_body = [](std::string_view sql) -> std::string {
        const auto open  = sql.find('(');
        const auto close = sql.rfind(')');
        return std::string(sql.substr(open + 1, close - open - 1));
    };

    EXPECT_EQ(extract_body(assigned_sql), extract_body(plain_sql))
            << "caller-assigned PK column definition must be byte-identical to plain primary on SQLite";
    EXPECT_TRUE(assigned_sql.contains("id INTEGER PRIMARY KEY"))
            << "expected plain INTEGER PRIMARY KEY in: " << assigned_sql;
    EXPECT_FALSE(assigned_sql.contains("AUTOINCREMENT"))
            << "caller-assigned must not emit AUTOINCREMENT: " << assigned_sql;
}

TEST(CallerAssignedPkSchemaTest, AssignedPkDdlMatchesPlainPrimaryPostgres) {
    const std::string& assigned_sql =
            storm::create_table_sql<AssignedIdModel, storm::orm::schema::Dialect::PostgreSQL>();
    const std::string& plain_sql =
            storm::create_table_sql<PlainPrimaryModel, storm::orm::schema::Dialect::PostgreSQL>();

    auto extract_body = [](std::string_view sql) -> std::string {
        const auto open  = sql.find('(');
        const auto close = sql.rfind(')');
        return std::string(sql.substr(open + 1, close - open - 1));
    };

    EXPECT_EQ(extract_body(assigned_sql), extract_body(plain_sql))
            << "caller-assigned PK column definition must be byte-identical to plain primary on PostgreSQL";
    EXPECT_TRUE(assigned_sql.contains("id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"))
            << "expected PG GENERATED BY DEFAULT in: " << assigned_sql;
    EXPECT_FALSE(assigned_sql.contains("AUTOINCREMENT")) << "PG must never emit AUTOINCREMENT: " << assigned_sql;
}

TEST(CallerAssignedPkSchemaTest, AutoincrementDdlUnchanged) {
    const std::string& autoinc_sql = storm::create_table_sql<AutoincModel>();
    EXPECT_TRUE(autoinc_sql.contains("id INTEGER PRIMARY KEY AUTOINCREMENT"))
            << "AUTOINCREMENT opt-in must be unchanged: " << autoinc_sql;

    const std::string& autoinc_pg = storm::create_table_sql<AutoincModel, storm::orm::schema::Dialect::PostgreSQL>();
    EXPECT_TRUE(autoinc_pg.contains("id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"))
            << "PG AUTOINCREMENT model must stay GENERATED BY DEFAULT: " << autoinc_pg;
    EXPECT_FALSE(autoinc_pg.contains("AUTOINCREMENT")) << "PG must never emit AUTOINCREMENT: " << autoinc_pg;
}
