#include <gtest/gtest.h>

#include "test_db_helpers.h"

// NOLINTBEGIN(misc-const-correctness)

import storm;
import std;

#include "test_models.h" // NOSONAR cpp:S954

// ============================================================================
// PK column name must come from the member's identifier, not a hardcoded "id"
// literal (#506). Every DML path (base.cppm's pk_name_) already reads the real
// identifier; the schema generator's CREATE TABLE branch — and the FK REFERENCES
// clause naming the TARGET model's PK — did not, so a model whose PK member is
// not called `id` got DDL and queries that disagreed ("no such column").
// ============================================================================

using storm::QuerySet;
using storm::orm::schema::Dialect;

namespace {

    // Single-PK model whose PK member is NOT named "id".
    struct Widget {
        [[= storm::primary]] int widget_id{};
        std::string              name;
    };

    // Single-PK model using primary_autoincrement with a non-"id" PK name — the
    // AUTOINCREMENT branch must also use the real identifier.
    struct Gadget {
        [[= storm::primary_autoincrement]] int gadget_id{};
        std::string                            name;
    };

    // FK TARGET whose PK member is not named "id". The REFERENCING model's FK
    // column must emit "REFERENCES Owner(owner_id)", not "REFERENCES Owner(id)".
    struct Owner {
        [[= storm::primary]] int owner_id{};
        std::string              label;
    };

    struct Item {
        [[= storm::primary]] int id{};
        [[= storm::fk<>]] Owner  owner;
        std::string              description;
    };

    // A deliberately long PK member name — proves the consteval size calculations
    // (column_size_budget's pk_size, col_def_buffer, calculate_column_defs_size)
    // were widened for a variable-length PK identifier rather than the fixed
    // literal "id", so this must build (and render untruncated) rather than
    // overflow the ConstexprString buffer at compile time.
    inline constexpr std::string_view kLongPkName =
            "this_is_a_deliberately_very_long_primary_key_identifier_that_exceeds_one_hundred_characters_long";

    struct LongPkNameRecord {
        [[= storm::primary]] int
                    this_is_a_deliberately_very_long_primary_key_identifier_that_exceeds_one_hundred_characters_long{};
        std::string name;
    };

    // A deliberately long PK name on an FK TARGET — proves fk_references_len /
    // max_fk_references_len were widened for a variable-length target PK
    // identifier too (not just the referencing side).
    struct LongPkTarget {
        [[= storm::primary]] int
                    this_is_a_deliberately_very_long_primary_key_identifier_that_exceeds_one_hundred_characters_long{};
        std::string label;
    };

    struct RefersToLongPkTarget {
        [[= storm::primary]] int       id{};
        [[= storm::fk<>]] LongPkTarget target;
    };

} // namespace

// fields:: selector proxies (#518). At global scope, NOT nested inside the
// anonymous namespace above: a nested `namespace fields` makes every
// unqualified `fields::` reference in this TU ambiguous against the global one.
namespace fields {

    struct WidgetT;
    consteval {
        std::meta::define_aggregate(^^WidgetT, storm::field_specs_for(^^Widget));
    }
    inline constexpr WidgetT Widget{};

} // namespace fields

// ============================================================================
// DDL — PK column name (SQLite + PostgreSQL)
// ============================================================================

TEST(PkColumnNameTest, NonIdPkNameEmittedSqlite) {
    const std::string& sql = storm::create_table_sql<Widget>();
    EXPECT_NE(sql.find("widget_id INTEGER PRIMARY KEY"), std::string::npos)
            << "Expected PK column named 'widget_id' in: " << sql;
    EXPECT_EQ(sql.find("    id "), std::string::npos) << "Must not fall back to the literal 'id' in: " << sql;
}

TEST(PkColumnNameTest, NonIdPkNameEmittedPostgres) {
    const std::string& sql = storm::create_table_sql<Widget, Dialect::PostgreSQL>();
    EXPECT_NE(sql.find("widget_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"), std::string::npos)
            << "Expected PK column named 'widget_id' in: " << sql;
}

TEST(PkColumnNameTest, NonIdPkNameWithAutoincrementSqlite) {
    const std::string& sql = storm::create_table_sql<Gadget>();
    EXPECT_NE(sql.find("gadget_id INTEGER PRIMARY KEY AUTOINCREMENT"), std::string::npos)
            << "Expected AUTOINCREMENT PK column named 'gadget_id' in: " << sql;
}

// Regression guard: Person's PK is named "id" — DDL must stay byte-identical.
TEST(PkColumnNameTest, IdNamedPkUnchanged) {
    const std::string& sql = storm::create_table_sql<Person>();
    EXPECT_NE(sql.find("    id INTEGER PRIMARY KEY,\n"), std::string::npos)
            << "Person's id-named PK DDL must be byte-identical: " << sql;
}

// A long PK name must not overflow the consteval size calculations (widened for
// a variable-length PK identifier, not the fixed literal "id") — proves the
// buffer, not just the column, and that it renders untruncated rather than
// std::unreachable()-ing at compile time (which would fail the build).
TEST(PkColumnNameTest, LongPkNameNotTruncatedSqlite) {
    const std::string& sql = storm::create_table_sql<LongPkNameRecord>();
    EXPECT_NE(sql.find(std::string(kLongPkName) + " INTEGER PRIMARY KEY"), std::string::npos)
            << "Long PK name was truncated in:\n"
            << sql;
}

TEST(PkColumnNameTest, LongPkNameNotTruncatedPostgres) {
    const std::string& sql = storm::create_table_sql<LongPkNameRecord, Dialect::PostgreSQL>();
    EXPECT_NE(
            sql.find(std::string(kLongPkName) + " BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY"),
            std::string::npos
    ) << "Long PK name was truncated in:\n"
      << sql;
}

// ============================================================================
// DDL — FK REFERENCES clause names the target's real PK (SQLite + PostgreSQL)
// ============================================================================

TEST(PkColumnNameTest, FkReferencesTargetNonIdPkSqlite) {
    const std::string& sql = storm::create_table_sql<Item>();
    EXPECT_NE(sql.find("owner_id INTEGER NOT NULL REFERENCES Owner(owner_id)"), std::string::npos)
            << "Expected REFERENCES Owner(owner_id) in: " << sql;
}

TEST(PkColumnNameTest, FkReferencesTargetNonIdPkPostgres) {
    const std::string& sql = storm::create_table_sql<Item, Dialect::PostgreSQL>();
    EXPECT_NE(sql.find("owner_id BIGINT NOT NULL REFERENCES Owner(owner_id)"), std::string::npos)
            << "Expected REFERENCES Owner(owner_id) in: " << sql;
}

// Regression guard: Message REFERENCES Person(id) — target's PK is "id" — must
// stay byte-identical.
TEST(PkColumnNameTest, FkReferencesIdNamedTargetUnchanged) {
    const std::string& sql = storm::create_table_sql<Message>();
    EXPECT_NE(sql.find("sender_id INTEGER NOT NULL REFERENCES Person(id)"), std::string::npos)
            << "Expected REFERENCES Person(id) unchanged in: " << sql;
}

// A long PK name on the FK TARGET must not overflow fk_references_len /
// max_fk_references_len (widened for a variable-length target PK identifier).
TEST(PkColumnNameTest, FkReferencesLongTargetPkNotTruncatedSqlite) {
    const std::string& sql = storm::create_table_sql<RefersToLongPkTarget>();
    EXPECT_NE(sql.find("REFERENCES LongPkTarget(" + std::string(kLongPkName) + ")"), std::string::npos)
            << "Long target PK name was truncated in:\n"
            << sql;
}

TEST(PkColumnNameTest, FkReferencesLongTargetPkNotTruncatedPostgres) {
    const std::string& sql = storm::create_table_sql<RefersToLongPkTarget, Dialect::PostgreSQL>();
    EXPECT_NE(sql.find("REFERENCES LongPkTarget(" + std::string(kLongPkName) + ")"), std::string::npos)
            << "Long target PK name was truncated in:\n"
            << sql;
}

// ============================================================================
// CRUD round-trip — non-"id" PK model (TYPED_TEST: SQLite + PostgreSQL)
//
// Proves DDL and DML agree: the generated column name and the WHERE/UPDATE/
// DELETE clause name (base.cppm's pk_name_, already correct pre-#506) refer to
// the same column.
// ============================================================================

template <typename ConnType> class NonIdPkCrudTest : public StormTestFixture<Widget, ConnType> {};

TYPED_TEST_SUITE(NonIdPkCrudTest, DatabaseTypes);

TYPED_TEST(NonIdPkCrudTest, InsertSelectUpdateDeleteRoundTrip) {
    using storm::orm::where::f;
    QuerySet<Widget, TypeParam> qs;

    auto inserted = qs.insert(Widget{.widget_id = 0, .name = "Sprocket"}).execute();
    ASSERT_TRUE(inserted.has_value()) << "Insert failed: "
                                      << (inserted.has_value() ? std::string{} : inserted.error().message());
    const auto new_id = static_cast<int>(inserted.value());

    auto selected = qs.where(fields::Widget.widget_id == new_id).select().execute();
    ASSERT_TRUE(selected.has_value()) << "Select by widget_id failed: "
                                      << (selected.has_value() ? std::string{} : selected.error().message());
    ASSERT_EQ(selected->size(), 1U);
    EXPECT_EQ(selected->begin()->name, "Sprocket");

    auto updated = qs.where(fields::Widget.widget_id == new_id)
                           .template update<^^Widget::name>(Widget{.name = "Cog"})
                           .execute();
    ASSERT_TRUE(updated.has_value()) << "Update by widget_id failed: "
                                     << (updated.has_value() ? std::string{} : updated.error().message());

    auto reselected = qs.where(fields::Widget.widget_id == new_id).select().execute();
    ASSERT_TRUE(reselected.has_value());
    ASSERT_EQ(reselected->size(), 1U);
    EXPECT_EQ(reselected->begin()->name, "Cog");

    auto deleted = qs.where(fields::Widget.widget_id == new_id).erase().execute();
    ASSERT_TRUE(deleted.has_value()) << "Delete by widget_id failed: "
                                     << (deleted.has_value() ? std::string{} : deleted.error().message());

    auto empty = qs.where(fields::Widget.widget_id == new_id).select().execute();
    ASSERT_TRUE(empty.has_value());
    EXPECT_EQ(empty->size(), 0U);
}

// ============================================================================
// FK-target-with-non-"id"-PK — executable DDL + working insert/join (TYPED_TEST)
// ============================================================================

template <typename ConnType> class FkTargetNonIdPkTest : public StormTestFixture<Owner, ConnType, Item> {};

TYPED_TEST_SUITE(FkTargetNonIdPkTest, DatabaseTypes);

TYPED_TEST(FkTargetNonIdPkTest, InsertWithFkToNonIdPkTargetSucceeds) {
    QuerySet<Owner, TypeParam> owner_qs;
    QuerySet<Item, TypeParam>  item_qs;

    auto owner_result = owner_qs.insert(Owner{.owner_id = 0, .label = "Acme"}).execute();
    ASSERT_TRUE(owner_result.has_value())
            << "Owner insert failed: " << (owner_result.has_value() ? std::string{} : owner_result.error().message());
    const auto owner_id = static_cast<int>(owner_result.value());

    auto item_result =
            item_qs.insert(Item{.id = 0, .owner = Owner{.owner_id = owner_id}, .description = "Widget A"}).execute();
    ASSERT_TRUE(item_result.has_value()) << "Item insert (FK to non-id PK target) failed: "
                                         << (item_result.has_value() ? std::string{} : item_result.error().message());

    auto joined = item_qs.template join<^^Item::owner>().select().execute();
    ASSERT_TRUE(joined.has_value()) << "Join on FK to non-id PK target failed: "
                                    << (joined.has_value() ? std::string{} : joined.error().message());
    ASSERT_EQ(joined->size(), 1U);
    EXPECT_EQ(joined->begin()->owner.label, "Acme");
}

// NOLINTEND(misc-const-correctness)
