#include <gtest/gtest.h>
#include <meta>

#include "test_db_helpers.h"

import storm;
import std;

#include "test_models.h" // NOSONAR cpp:S954 — Person, the single-PK regression anchor

// ============================================================================
// #586: a caller-assigned integer primary key is never DB-generated, so nothing
// is RETURNed and the PK column IS emitted in INSERT.
//
// This is the integer half of the same rule #502 established for composite keys
// and #572 extended to UUID keys: a key the caller supplies cannot be echoed back
// by RETURNING, because the caller already has it. The difference from those two
// is that a single-column INTEGER key is the shape Storm previously classified
// as DB-generated unconditionally — so this issue adds a new annotation
// (storm::primary_assigned) that flips the predicate.
//
// Round-tripped on both backends: SQLite and PG disagree about what is an error
// in this area (PG enforces GENERATED BY DEFAULT strictly; SQLite silently
// accepts a caller-supplied rowid value).
// ============================================================================

// NOLINTBEGIN(readability-implicit-bool-conversion)

namespace {

    // Minimal model with a caller-assigned integer primary key (#586).
    struct AssignedIdRec {
        [[= storm::primary_assigned]] std::int64_t ext_id{};
        std::string                                label;
    };

    // A second model with a non-"id" PK name — RETURNING would name the pk
    // column, so a hardcoded "id" would sit dead behind the same branch.
    struct AssignedRefRec {
        [[= storm::primary_assigned]] std::int64_t ref_code{};
        std::string                                description;
    };

    // The regression anchor: a plain single-INTEGER PK must keep the RETURNING
    // path byte-for-byte, since that is the one shape a DB really does generate.
    struct AutoIdRec {
        [[= storm::primary]] std::int64_t id{};
        std::string                       label;
    };

    // The OTHER non-generated shape. This TU is about caller-assigned integer
    // keys, but the fix's thesis is that ONE predicate now serves all three
    // non-generated shapes — so without a composite model here, narrowing
    // pk_is_db_generated_() back to `!has_caller_assigned_pk_()` would leave
    // every assertion below green while silently regressing composite INSERT
    // and upsert (#502/#503). Asserted, not round-tripped: the composite
    // behaviour itself is owned by test_composite_pk_sql.cpp /
    // test_composite_pk_crud.cpp, and what needs pinning HERE is only that all
    // three shapes share the one gate.
    struct CompositeNoteRec {
        [[= storm::primary_part]] std::int64_t region{};
        [[= storm::primary_part]] std::int64_t slot{};
        std::string                            title;
    };

} // namespace

namespace fields {

    struct AssignedIdRecT;
    consteval {
        std::meta::define_aggregate(^^AssignedIdRecT, storm::field_specs_for(^^AssignedIdRec));
    }
    inline constexpr AssignedIdRecT AssignedIdRec{};

    struct AssignedRefRecT;
    consteval {
        std::meta::define_aggregate(^^AssignedRefRecT, storm::field_specs_for(^^AssignedRefRec));
    }
    inline constexpr AssignedRefRecT AssignedRefRec{};

    struct AutoIdRecT;
    consteval {
        std::meta::define_aggregate(^^AutoIdRecT, storm::field_specs_for(^^AutoIdRec));
    }
    inline constexpr AutoIdRecT AutoIdRec{};

} // namespace fields

// ============================================================================
// Compile-time gates
// ============================================================================

namespace {

    using storm::orm::statements::default_return_id;
    using storm::orm::statements::ReturnId;
    using storm::orm::statements::ReturnIdSupported;

    // (1) The default plain insert() resolves to.
    static_assert(
            default_return_id<AssignedIdRec>() == ReturnId::No,
            "plain insert() on a caller-assigned-PK model resolves to the void path — nothing is DB-generated"
    );
    static_assert(
            default_return_id<AssignedRefRec>() == ReturnId::No,
            "the default is driven by the key ANNOTATION, not by the member being named 'id'"
    );
    static_assert(
            default_return_id<AutoIdRec>() == ReturnId::Yes,
            "plain insert() on a single-integer-PK model still returns the generated id"
    );
    // The shared-gate assertions: pk_is_db_generated_() must answer FALSE for all
    // three non-generated shapes. Narrowing it to `!has_caller_assigned_pk_()`
    // passes every other assertion in this TU and fails only these.
    static_assert(
            default_return_id<CompositeNoteRec>() == ReturnId::No,
            "the predicate this issue introduced must still cover composite keys (#502)"
    );

    // (2) ReturnIdSupported gate.
    static_assert(
            !ReturnIdSupported<AssignedIdRec, ReturnId::Yes>,
            "an explicit ReturnId::Yes on a caller-assigned-PK model must be rejected, not silently lossy"
    );
    static_assert(
            !ReturnIdSupported<AssignedRefRec, ReturnId::Yes>, "the gate does not depend on the key member's name"
    );
    static_assert(ReturnIdSupported<AssignedIdRec, ReturnId::No>, "ReturnId::No stays valid on every model shape");
    static_assert(ReturnIdSupported<AutoIdRec, ReturnId::Yes>, "a single-integer-PK model keeps the RETURNING path");
    static_assert(
            !ReturnIdSupported<CompositeNoteRec, ReturnId::Yes>,
            "the gate is shared between all three non-generated shapes"
    );

    // (3) The gate is WIRED to the public entry points.
    template <typename Model, typename ConnType>
    concept SingleInsertYesCallable = requires(storm::QuerySet<Model, ConnType>& qs, const Model& obj) {
        qs.template insert<ReturnId::Yes>(obj);
    };
    template <typename Model, typename ConnType>
    concept BulkInsertYesCallable = requires(storm::QuerySet<Model, ConnType>& qs, std::span<const Model> objs) {
        qs.template insert<ReturnId::Yes>(objs);
    };

    using Sqlite = storm::db::sqlite::Connection;

    static_assert(
            !SingleInsertYesCallable<AssignedIdRec, Sqlite>,
            "qs.insert<ReturnId::Yes>(assigned_pk_model) must fail at the CALL SITE"
    );
    static_assert(
            !BulkInsertYesCallable<AssignedIdRec, Sqlite>,
            "bulk insert<ReturnId::Yes>(assigned_pk_model) must fail at the CALL SITE"
    );

} // namespace

// ============================================================================
// SQL text — the column list and RETURNING clause are the primary regression
// risk. A disagreement between FieldNameGrammar::is_skipped_pk and
// BaseStatement::skips_pk_column misaligns columns against values silently.
// ============================================================================

namespace {

    template <typename T> auto insert_void_sql() -> std::string {
        return storm::orm::statements::InsertStatement<T, storm::db::sqlite::Connection>::VoidQuery::sql();
    }

    template <typename T> auto default_insert_sql() -> std::string {
        using storm::orm::statements::default_return_id;
        using storm::orm::statements::ReturnId;
        using Stmt = storm::orm::statements::InsertStatement<T, storm::db::sqlite::Connection>;
        if constexpr (default_return_id<T>() == ReturnId::Yes) {
            return Stmt::SingleQuery::sql();
        } else {
            return Stmt::VoidQuery::sql();
        }
    }

} // namespace

TEST(CallerAssignedPkSqlTest, InsertEmitsPkColumnAndNoReturning) {
    const std::string& sql = insert_void_sql<AssignedIdRec>();
    EXPECT_TRUE(sql.starts_with("INSERT INTO AssignedIdRec (ext_id, label) VALUES (?, ?)"))
            << "PK column must be present in the INSERT column list: " << sql;
    EXPECT_FALSE(sql.contains("RETURNING")) << "no RETURNING for a caller-assigned key: " << sql;
}

TEST(CallerAssignedPkSqlTest, InsertWithNonIdPkNameEmitsCorrectColumn) {
    const std::string& sql = insert_void_sql<AssignedRefRec>();
    EXPECT_TRUE(sql.starts_with("INSERT INTO AssignedRefRec (ref_code, description) VALUES (?, ?)"))
            << "PK column name must be the real identifier, not a hardcoded 'id': " << sql;
    EXPECT_FALSE(sql.contains("RETURNING")) << "no RETURNING for a caller-assigned key: " << sql;
}

TEST(CallerAssignedPkSqlTest, AutoIdInsertStillReturnsId) {
    const std::string& sql = default_insert_sql<AutoIdRec>();
    EXPECT_TRUE(sql.ends_with("RETURNING id")) << "plain primary INSERT must still RETURN id: " << sql;
}

// ============================================================================
// Round-trip: INSERT + SELECT on a live backend
//
// Fixture pattern: anchor on Person (for PG schema init), create the AssignedIdRec
// table from generated DDL in on_setup — same pattern as CompositePkFixture in
// test_composite_pk_crud.cpp.
// ============================================================================

template <typename ConnType> class CallerAssignedPkCrudTest : public StormTestFixture<Person, ConnType> {
  public:
    auto on_setup(const std::shared_ptr<ConnType>& conn) -> void override {
        const std::string ddl =
                storm::test::is_postgresql<ConnType>()
                        ? storm::create_table_sql<AssignedIdRec, storm::orm::schema::Dialect::PostgreSQL>()
                        : storm::create_table_sql<AssignedIdRec>();
        ASSERT_TRUE(conn->execute(ddl).has_value()) << ddl;
    }
};

TYPED_TEST_SUITE(CallerAssignedPkCrudTest, DatabaseTypes);

TYPED_TEST(CallerAssignedPkCrudTest, InsertPersistsCallerSuppliedId) {
    storm::QuerySet<AssignedIdRec, TypeParam> qs;
    const AssignedIdRec                       row{.ext_id = 42, .label = "imported"};
    auto                                      result = qs.insert(row).execute();

    static_assert(
            std::is_same_v<decltype(result), std::expected<void, typename TypeParam::Error>>,
            "insert() on a caller-assigned-PK model returns void — nothing to RETURN"
    );
    ASSERT_TRUE(result.has_value()) << result.error().message();

    auto selected = qs.select().execute();
    ASSERT_TRUE(selected.has_value()) << selected.error().message();
    ASSERT_EQ(selected.value().size(), 1U);
    const auto& loaded = *selected.value().begin();
    EXPECT_EQ(loaded.ext_id, 42) << "the caller's id value must survive round-trip";
    EXPECT_EQ(loaded.label, "imported");
}

TYPED_TEST(CallerAssignedPkCrudTest, InsertWithZeroIdPersistsZero) {
    storm::QuerySet<AssignedIdRec, TypeParam> qs;
    const AssignedIdRec                       row{.ext_id = 0, .label = "zero"};
    auto                                      result = qs.insert(row).execute();
    ASSERT_TRUE(result.has_value()) << result.error().message();

    auto selected = qs.where(fields::AssignedIdRec.ext_id == 0).select().execute();
    ASSERT_TRUE(selected.has_value()) << selected.error().message();
    ASSERT_EQ(selected.value().size(), 1U);
    EXPECT_EQ(selected.value().begin()->label, "zero");
}

TYPED_TEST(CallerAssignedPkCrudTest, SecondInsertWithSameIdIsDuplicateError) {
    storm::QuerySet<AssignedIdRec, TypeParam> qs;
    ASSERT_TRUE(qs.insert(AssignedIdRec{.ext_id = 100, .label = "first"}).execute().has_value());

    auto duplicate = qs.insert(AssignedIdRec{.ext_id = 100, .label = "second"}).execute();
    EXPECT_FALSE(duplicate.has_value()) << "duplicate caller-assigned PK must be rejected by the database";
}

// ============================================================================
// ON CONFLICT (#585): a caller-assigned key IS a valid conflict target because
// it IS present in the INSERT — a duplicate really collides.
// ============================================================================

template <typename ConnType> class CallerAssignedPkUpsertTest : public StormTestFixture<Person, ConnType> {
  public:
    auto on_setup(const std::shared_ptr<ConnType>& conn) -> void override {
        const std::string ddl =
                storm::test::is_postgresql<ConnType>()
                        ? storm::create_table_sql<AssignedIdRec, storm::orm::schema::Dialect::PostgreSQL>()
                        : storm::create_table_sql<AssignedIdRec>();
        ASSERT_TRUE(conn->execute(ddl).has_value()) << ddl;
    }
};

TYPED_TEST_SUITE(CallerAssignedPkUpsertTest, DatabaseTypes);

TYPED_TEST(CallerAssignedPkUpsertTest, DoNothingSkipsOnDuplicateKey) {
    storm::QuerySet<AssignedIdRec, TypeParam> qs;
    ASSERT_TRUE(qs.insert(AssignedIdRec{.ext_id = 200, .label = "original"}).execute().has_value());

    auto upserted = qs.insert(AssignedIdRec{.ext_id = 200, .label = "clash"})
                            .template on_conflict<fields::AssignedIdRec.ext_id>()
                            .nothing()
                            .execute();

    static_assert(
            std::is_same_v<decltype(upserted), std::expected<void, typename TypeParam::Error>>,
            "DO NOTHING on a caller-assigned-PK model returns void"
    );
    ASSERT_TRUE(upserted.has_value()) << upserted.error().message();

    auto selected = qs.select().execute();
    ASSERT_TRUE(selected.has_value()) << selected.error().message();
    ASSERT_EQ(selected.value().size(), 1U);
    EXPECT_EQ(selected.value().begin()->label, "original") << "DO NOTHING must not overwrite";
}

TYPED_TEST(CallerAssignedPkUpsertTest, DoUpdateOverwritesOnDuplicateKey) {
    storm::QuerySet<AssignedIdRec, TypeParam> qs;
    ASSERT_TRUE(qs.insert(AssignedIdRec{.ext_id = 300, .label = "old"}).execute().has_value());

    auto upserted = qs.insert(AssignedIdRec{.ext_id = 300, .label = "new"})
                            .template on_conflict<fields::AssignedIdRec.ext_id>()
                            .template update<fields::AssignedIdRec.label>()
                            .execute();

    static_assert(
            std::is_same_v<decltype(upserted), std::expected<void, typename TypeParam::Error>>,
            "DO UPDATE on a caller-assigned-PK model returns void"
    );
    ASSERT_TRUE(upserted.has_value()) << upserted.error().message();

    auto selected = qs.where(fields::AssignedIdRec.ext_id == 300).select().execute();
    ASSERT_TRUE(selected.has_value()) << selected.error().message();
    ASSERT_EQ(selected.value().size(), 1U);
    EXPECT_EQ(selected.value().begin()->label, "new") << "DO UPDATE must overwrite the listed column";
}

// ============================================================================
// Batch insert
// ============================================================================

template <typename ConnType> class CallerAssignedPkBatchTest : public StormTestFixture<Person, ConnType> {
  public:
    auto on_setup(const std::shared_ptr<ConnType>& conn) -> void override {
        const std::string ddl =
                storm::test::is_postgresql<ConnType>()
                        ? storm::create_table_sql<AssignedIdRec, storm::orm::schema::Dialect::PostgreSQL>()
                        : storm::create_table_sql<AssignedIdRec>();
        ASSERT_TRUE(conn->execute(ddl).has_value()) << ddl;
    }
};

TYPED_TEST_SUITE(CallerAssignedPkBatchTest, DatabaseTypes);

TYPED_TEST(CallerAssignedPkBatchTest, BatchInsertPersistsAllIds) {
    storm::QuerySet<AssignedIdRec, TypeParam> qs;
    std::vector<AssignedIdRec>                batch = {
            {.ext_id = 1001, .label = "a"},
            {.ext_id = 1002, .label = "b"},
            {.ext_id = 1003, .label = "c"},
    };
    auto result = qs.insert(std::span<const AssignedIdRec>(batch)).execute();
    ASSERT_TRUE(result.has_value()) << result.error().message();

    auto selected = qs.select().execute();
    ASSERT_TRUE(selected.has_value()) << selected.error().message();
    EXPECT_EQ(selected.value().size(), 3U);

    std::set<std::int64_t> ids;
    for (const auto& row : selected.value()) {
        ids.insert(row.ext_id);
    }
    EXPECT_EQ(ids, (std::set<std::int64_t>{1001, 1002, 1003})) << "all caller-supplied ids must be present";
}

// NOLINTEND(readability-implicit-bool-conversion)
