#!/usr/bin/env bash
# Integration test: storm-schema -> Atlas -> verify DB structure
# Usage: ./scripts/test-atlas-migration.sh [--build-dir BUILD_DIR]
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

BUILD_DIR="build/debug"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --build-dir) BUILD_DIR="$2"; shift 2 ;;
        *) echo -e "${RED}Unknown arg: $1${NC}"; exit 1 ;;
    esac
done

SCHEMA_BIN="${BUILD_DIR}/tests/tools/storm_schema/storm_schema"
TMPDIR=$(mktemp -d /tmp/storm_atlas_test_XXXXXX)
trap 'rm -rf "${TMPDIR}"' EXIT

pass=0
fail=0

ok() {
    echo -e "  ${GREEN}PASS${NC} $1"
    pass=$((pass + 1))
}

ko() {
    echo -e "  ${RED}FAIL${NC} $1"
    fail=$((fail + 1))
}

# ── Prerequisites ────────────────────────────────────────────────────────────

echo -e "${YELLOW}=== Storm Atlas Integration Test ===${NC}"
echo ""

if ! command -v atlas &>/dev/null; then
    echo -e "${RED}atlas CLI not found. Install: curl -sSf https://atlasgo.sh | sh${NC}"
    exit 1
fi

if [[ ! -x "${SCHEMA_BIN}" ]]; then
    echo -e "${RED}storm_schema not found at ${SCHEMA_BIN}${NC}"
    echo "Build it first: cmake --build --preset ninja-debug --target storm_schema"
    exit 1
fi

if ! command -v sqlite3 &>/dev/null; then
    echo -e "${RED}sqlite3 CLI not found${NC}"
    exit 1
fi

# ── Test 1: Schema export ────────────────────────────────────────────────────

echo -e "${YELLOW}1. Schema export${NC}"

"${SCHEMA_BIN}" --output "${TMPDIR}/schema_sqlite.sql"
[[ -s "${TMPDIR}/schema_sqlite.sql" ]] && ok "SQLite schema file generated" || ko "SQLite schema file generated"

"${SCHEMA_BIN}" --dialect postgresql --output "${TMPDIR}/schema_pg.sql"
[[ -s "${TMPDIR}/schema_pg.sql" ]] && ok "PostgreSQL schema file generated" || ko "PostgreSQL schema file generated"

grep -q "CREATE TABLE Person" "${TMPDIR}/schema_sqlite.sql" && ok "SQLite: CREATE TABLE Person" || ko "SQLite: CREATE TABLE Person"
grep -q "CREATE TABLE Message" "${TMPDIR}/schema_sqlite.sql" && ok "SQLite: CREATE TABLE Message" || ko "SQLite: CREATE TABLE Message"
grep -q "CREATE TABLE SimpleRecord" "${TMPDIR}/schema_sqlite.sql" && ok "SQLite: CREATE TABLE SimpleRecord" || ko "SQLite: CREATE TABLE SimpleRecord"
grep -q "CREATE TABLE ExtendedTypes" "${TMPDIR}/schema_sqlite.sql" && ok "SQLite: CREATE TABLE ExtendedTypes" || ko "SQLite: CREATE TABLE ExtendedTypes"
grep -q "CREATE TABLE Task" "${TMPDIR}/schema_sqlite.sql" && ok "SQLite: CREATE TABLE Task" || ko "SQLite: CREATE TABLE Task"
grep -q "GENERATED BY DEFAULT AS IDENTITY" "${TMPDIR}/schema_pg.sql" && ok "PostgreSQL: GENERATED BY DEFAULT AS IDENTITY" || ko "PostgreSQL: GENERATED BY DEFAULT AS IDENTITY"

# ── Test 2: Atlas schema apply (declarative) ────────────────────────────────

echo ""
echo -e "${YELLOW}2. Atlas schema apply (declarative)${NC}"

TESTDB="${TMPDIR}/test.db"
if atlas schema apply \
    --url "sqlite://${TESTDB}" \
    --to "file://${TMPDIR}/schema_sqlite.sql" \
    --dev-url "sqlite://dev?mode=memory" \
    --auto-approve >/dev/null 2>&1; then
    ok "atlas schema apply succeeds"
else
    ko "atlas schema apply succeeds"
fi

TABLES=$(sqlite3 "${TESTDB}" ".tables" 2>/dev/null || echo "")
for tbl in Person SimpleRecord Message ExtendedTypes Task; do
    echo "${TABLES}" | grep -q "${tbl}" && ok "${tbl} table exists" || ko "${tbl} table exists"
done

PERSON_COLS=$(sqlite3 "${TESTDB}" "PRAGMA table_info(Person);" 2>/dev/null || echo "")
for col in id name age salary department; do
    echo "${PERSON_COLS}" | grep -q "${col}" && ok "Person.${col} column exists" || ko "Person.${col} column exists"
done

INDEXES=$(sqlite3 "${TESTDB}" "SELECT name FROM sqlite_master WHERE type='index';" 2>/dev/null || echo "")
for idx in idx_Person_department idx_Person_department_age idx_Person_name_department idx_Message_sender_id idx_Task_assignee_id; do
    echo "${INDEXES}" | grep -q "${idx}" && ok "${idx} index exists" || ko "${idx} index exists"
done

# ── Test 3: Idempotency ─────────────────────────────────────────────────────

echo ""
echo -e "${YELLOW}3. Idempotency${NC}"

APPLY_OUTPUT=$(atlas schema apply \
    --url "sqlite://${TESTDB}" \
    --to "file://${TMPDIR}/schema_sqlite.sql" \
    --dev-url "sqlite://dev?mode=memory" \
    --auto-approve 2>&1 || true)
echo "${APPLY_OUTPUT}" | grep -q "Schema is synced" && ok "Re-apply is no-op" || ko "Re-apply is no-op"

# ── Test 4: Atlas versioned migration validate ───────────────────────────────

echo ""
echo -e "${YELLOW}4. Versioned migration validate${NC}"

if [[ -d "tests/tools/migrations" ]]; then
    if atlas migrate validate --dir "file://tests/tools/migrations" --dev-url "sqlite://dev?mode=memory" 2>/dev/null; then
        ok "atlas migrate validate passes"
    else
        ko "atlas migrate validate passes"
    fi
else
    echo -e "  ${YELLOW}SKIP${NC} No migrations/ directory"
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
TOTAL=$((pass + fail))
echo -e "${YELLOW}=== Results: ${pass}/${TOTAL} passed ===${NC}"
if [[ ${fail} -gt 0 ]]; then
    echo -e "${RED}${fail} test(s) failed${NC}"
    exit 1
fi
echo -e "${GREEN}All tests passed${NC}"
